### ISSUE TITLE
Cannot use npx polar-init at all!

### ISSUE THREAD

**Issue by salvinoto** [polarsource/polar-init#6]
Hi, very plain issue, I'm getting a 404 when running npx polar-init. Thanks!
 npx polar-init
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/polar-init - Not found
npm error 404
npm error 404  'polar-init@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /Users/salvatorenoto/.npm/_logs/2024-12-08T18_25_09_422Z-debug-0.log

**Comment by emilwidlund** [comment]
@salvinoto Thanks for reporting. Looks like npm is currently doing infrastructure updates.
<img width="1010" alt="Screenshot 2024-12-08 at 19 36 30" src="https://github.com/user-attachments/assets/41eb5878-55ec-4403-ae68-7b2ebe8161e5">

**Comment by salvinoto** [comment]
Just realized that, once all of my packages stopped working! Thank you.
